/** Iconify classes used by Inkfinite's shared icon component. */
export const ICONS = {
	add: 'i-ph-plus-bold',
	arrow: 'i-tabler-arrow-up-right',
	'arrow-down': 'i-tabler-arrow-down',
	'arrow-right': 'i-tabler-arrow-right',
	'arrow-left': 'i-tabler-arrow-left',
	'arrow-up': 'i-tabler-arrow-up',
	check: 'i-bi-check-lg',
	'chevron-left': 'i-tabler-chevron-left',
	'chevron-right': 'i-tabler-chevron-right',
	close: 'i-ph-x-bold',
	copy: 'i-ph-copy',
	dark: 'i-tabler-moon',
	delete: 'i-bi-trash3',
	'dots-vertical': 'i-tabler-dots-vertical',
	expand: 'i-bi-arrows-angle-expand',
	draw: 'i-ph-pencil-simple-line-bold',
	eye: 'i-tabler-eye',
	'eye-off': 'i-tabler-eye-off',
	'external-link': 'i-tabler-external-link',
	folder: 'i-ph-folder-bold',
	github: 'i-tabler-brand-github',
	'grid-dots': 'i-tabler-grid-dots',
	'grip-vertical': 'i-tabler-grip-vertical',
	history: 'i-tabler-history',
	'info-circle': 'i-tabler-info-circle',
	light: 'i-tabler-sun',
	menu: 'i-bi-list',
	markdown: 'i-tabler-markdown',
	line: 'i-tabler-minus',
	layers: 'i-tabler-layers-subtract',
	lock: 'i-tabler-lock',
	'lock-open': 'i-tabler-lock-open',
	ellipse: 'i-tabler-circle',
	rectangle: 'i-tabler-rectangle',
	select: 'i-tabler-pointer',
	'direct-select': 'i-tabler-point',
	text: 'i-tabler-letter-t',
	terminal: 'i-tabler-terminal-2',
	moon: 'i-tabler-moon',
	pencil: 'i-ph-pencil-simple-line-bold',
	redo: 'i-tabler-arrow-forward-up',
	save: 'i-ph-floppy-disk-back-bold',
	search: 'i-ph-magnifying-glass-bold',
	settings: 'i-bi-sliders',
	shapes: 'i-ph-shapes-light',
	sun: 'i-tabler-sun',
	trash: 'i-bi-trash3',
	undo: 'i-tabler-arrow-back-up',
	svg: 'i-tabler-svg',
	'book-open': 'i-ph-book-open-light'
} as const;

/** A semantic icon name supported by the shared icon component. */
export type IconName = keyof typeof ICONS;
