[workspace]
members = [
  "apps/desktop/src-tauri",
  "crates/inkfinite-cli",
  "crates/inkfinite-core",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-only"
rust-version = "1.89"
version = "0.0.0"

[workspace.dependencies]
automerge = "=0.10.0"
inkfinite-core = { path = "crates/inkfinite-core" }
schemars = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ts-rs = { version = "12.0.1", features = ["no-serde-warnings", "serde-json-impl"] }
thiserror = "2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
