import { readFile, writeFile } from "node:fs/promises";

import { createGenerator } from "unocss";

import config from "../uno.config.mjs";

const generator = await createGenerator(config);
const iconSource = await readFile(new URL("../src/lib/icons.ts", import.meta.url), "utf8");
const { css } = await generator.generate(iconSource, { preflights: false });

if (!css.trim()) {
  throw new Error("UnoCSS did not generate any icons from src/lib/icons.ts");
}

await writeFile(
  new URL("../src/lib/styles/icons.css", import.meta.url),
  `/* Generated by \`pnpm icons:generate\`. Do not edit directly. */\n${css}\n`,
);
