[package]
name = "xtask"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
inkfinite-cli = { path = "../crates/inkfinite-cli" }
sha2.workspace = true

[lints]
workspace = true
