[package]
name = "inkfinite-cli"
description = "Command-line entry point for Inkfinite"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "inkfinite"
path = "src/bin/inkfinite-cli.rs"

[[bin]]
name = "generate-bindings"
path = "src/bin/generate-bindings.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
inkfinite-core.workspace = true
resvg.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
ts-rs.workspace = true

[lints]
workspace = true
