// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

import type {
	ActorId,
	BindingAnchor,
	BindingId,
	BindingKind,
	BindingRecord,
	ContainerLayout,
	LayerId,
	LayerRecord,
	Opacity,
	Origin,
	PageId,
	PageRecord,
	SemanticMetadata,
	ShapeId,
	ShapeKind,
	ShapeParent,
	ShapeProperties,
	ShapeStyle,
	SiblingAnchor,
	Timestamp
} from './model.js';
import type { LayerContentsDisposition, LayerPatch, TransactionId } from './transaction.js';

/**
 * Full affine transform used by the editor projection.
 *
 * Unlike the canonical [`Transform`], this representation can retain the
 * result of composing ancestor transforms even when the composition includes
 * non-uniform scale and rotation.
 */
export type EditorTransform = {
	/**
	 * Horizontal scale and rotation component.
	 */
	a: number;
	/**
	 * Vertical shear and rotation component.
	 */
	b: number;
	/**
	 * Horizontal shear and rotation component.
	 */
	c: number;
	/**
	 * Vertical scale and rotation component.
	 */
	d: number;
	/**
	 * Horizontal translation.
	 */
	e: number;
	/**
	 * Vertical translation.
	 */
	f: number;
};

/**
 * One shape projected into the editor's flat depth-first shape collection.
 *
 * Containers are included so the editor can select them as one object and
 * enter their child scope. They have no direct drawing primitive; their
 * descendants remain in the same depth-first order.
 */
export type EditorShape = {
	/**
	 * Stable shape identifier.
	 */
	id: ShapeId;
	/**
	 * Editor registry key.
	 */
	type: ShapeKind;
	/**
	 * Page containing the shape.
	 */
	page_id: PageId;
	/**
	 * Complete native-to-world transform.
	 */
	transform: EditorTransform;
	/**
	 * Legacy translation fields used by the current editor interaction model.
	 */
	x: number;
	/**
	 * Legacy translation field used by the current editor interaction model.
	 */
	y: number;
	/**
	 * Legacy rotation field used by the current editor interaction model.
	 */
	rot: number;
	/**
	 * Immediate container parent, when the shape is inside a container.
	 */
	group_id: ShapeId | null;
	/**
	 * Owning editor layer.
	 */
	layer_id: LayerId;
	/**
	 * Complete-shape opacity.
	 */
	opacity: Opacity;
	/**
	 * Optional fill opacity.
	 */
	fill_opacity: Opacity | null;
	/**
	 * Optional stroke opacity.
	 */
	stroke_opacity: Opacity | null;
	/**
	 * Whether this shape and its descendants can be edited.
	 */
	locked: boolean;
	/**
	 * Agent editability retained for editor policy surfaces.
	 */
	agent_editable: boolean;
	/**
	 * Kind-specific properties using editor property names.
	 */
	props: ShapeProperties;
};

/**
 * A new shape supplied by an editor patch.
 */
export type EditorShapeDraft = {
	/**
	 * Stable shape identifier.
	 */
	id: ShapeId;
	/**
	 * Native registry key.
	 */
	kind: ShapeKind;
	/**
	 * Kind-specific properties using editor property names.
	 */
	properties: ShapeProperties;
	/**
	 * Optional semantic metadata. Missing metadata receives editor defaults.
	 */
	metadata: SemanticMetadata | null;
	/**
	 * Common visual style.
	 */
	style: ShapeStyle;
	/**
	 * Optional container layout.
	 */
	layout: ContainerLayout | null;
};

/**
 * Page represented in the flat editor document.
 */
export type EditorPage = {
	/**
	 * Stable page identifier.
	 */
	id: PageId;
	/**
	 * User-visible page name.
	 */
	name: string;
	/**
	 * Shape IDs in depth-first draw order, including containers.
	 */
	shape_ids: Array<ShapeId>;
	/**
	 * Layer IDs in back-to-front order.
	 */
	layer_ids: Array<LayerId>;
};

/**
 * Layer represented in the flat editor document.
 */
export type EditorLayer = {
	/**
	 * Stable layer identifier.
	 */
	id: LayerId;
	/**
	 * Owning page identifier.
	 */
	page_id: PageId;
	/**
	 * User-visible layer name.
	 */
	name: string;
	/**
	 * Shape IDs in depth-first draw order, including containers.
	 */
	shape_ids: Array<ShapeId>;
	/**
	 * Whether the layer participates in rendering.
	 */
	visible: boolean;
	/**
	 * Whether the layer can be selected or changed.
	 */
	locked: boolean;
	/**
	 * Inherited layer opacity.
	 */
	opacity: Opacity;
};

/**
 * Binding represented in the editor's binding collection.
 */
export type EditorBinding = {
	/**
	 * Stable binding identifier.
	 */
	id: BindingId;
	/**
	 * Editor binding kind.
	 */
	type: BindingKind;
	/**
	 * Source arrow or connector.
	 */
	from_shape_id: ShapeId;
	/**
	 * Target shape.
	 */
	to_shape_id: ShapeId;
	/**
	 * Source handle.
	 */
	handle: string;
	/**
	 * Target anchor.
	 */
	anchor: BindingAnchor;
};

/**
 * Ordering information accompanying an editor projection.
 */
export type EditorOrder = {
	/**
	 * Page IDs in document order.
	 */
	page_ids: Array<PageId>;
	/**
	 * Flattened depth-first shape order by page.
	 */
	shape_order: { [key in PageId]: Array<ShapeId> };
	/**
	 * Layer records in their projected form.
	 */
	layers: { [key in LayerId]: EditorLayer };
};

/**
 * Native document projected into the editor's flat document shape.
 */
export type EditorProjection = {
	/**
	 * Projected pages.
	 */
	pages: { [key in PageId]: EditorPage };
	/**
	 * Projected layers.
	 */
	layers: { [key in LayerId]: EditorLayer };
	/**
	 * Shapes with composed world transforms, including containers.
	 */
	shapes: { [key in ShapeId]: EditorShape };
	/**
	 * Projected bindings.
	 */
	bindings: { [key in BindingId]: EditorBinding };
	/**
	 * Stable ordering metadata.
	 */
	order: EditorOrder;
};

/**
 * Semantic editor changes that can be reconciled into native operations.
 *
 * Shape transforms are world-space transforms from [`EditorShape::transform`].
 * The reconciler converts them back to parent-relative canonical transforms.
 */
export type EditorPatch =
	| {
			type: 'shape';
			/**
			 * Shape to change.
			 */
			shape_id: ShapeId;
			/**
			 * Replacement world-space transform.
			 */
			transform: EditorTransform | null;
			/**
			 * Replacement editor properties.
			 */
			properties: ShapeProperties | null;
			/**
			 * Replacement semantic metadata.
			 */
			metadata: SemanticMetadata | null;
			/**
			 * Replacement visual style.
			 */
			style: ShapeStyle | null;
			/**
			 * Replacement parent, when reparenting is part of the edit.
			 */
			parent: ShapeParent | null;
			/**
			 * Replacement sibling placement.
			 */
			anchor: SiblingAnchor<ShapeId> | null;
	  }
	| {
			type: 'create_page';
			/**
			 * New page record.
			 */
			page: PageRecord;
			/**
			 * Placement relative to an existing page.
			 */
			anchor: SiblingAnchor<PageId>;
	  }
	| {
			type: 'delete_page';
			/**
			 * Page to delete.
			 */
			page_id: PageId;
	  }
	| {
			type: 'create_layer';
			/**
			 * New layer record.
			 */
			layer: LayerRecord;
			/**
			 * Placement relative to an existing layer.
			 */
			anchor: SiblingAnchor<LayerId>;
	  }
	| {
			type: 'delete_layer';
			/**
			 * Layer to delete.
			 */
			layer_id: LayerId;
			/**
			 * Handling for shapes owned by the layer.
			 */
			contents: LayerContentsDisposition;
	  }
	| {
			type: 'create_shape';
			/**
			 * New shape fields.
			 */
			shape: EditorShapeDraft;
			/**
			 * Parent in the native hierarchy.
			 */
			parent: ShapeParent;
			/**
			 * World-space transform for the new shape.
			 */
			transform: EditorTransform;
			/**
			 * Sibling placement.
			 */
			anchor: SiblingAnchor<ShapeId>;
	  }
	| {
			type: 'delete_shape';
			/**
			 * Shape to delete.
			 */
			shape_id: ShapeId;
	  }
	| {
			type: 'rename_page';
			/**
			 * Page to rename.
			 */
			page_id: PageId;
			/**
			 * Replacement page name.
			 */
			name: string;
	  }
	| {
			type: 'patch_layer';
			/**
			 * Layer to change.
			 */
			layer_id: LayerId;
			/**
			 * Replacement fields.
			 */
			patch: LayerPatch;
	  }
	| {
			type: 'reorder_layer';
			/**
			 * Layer to move.
			 */
			layer_id: LayerId;
			/**
			 * Replacement placement.
			 */
			anchor: SiblingAnchor<LayerId>;
	  }
	| {
			type: 'create_binding';
			/**
			 * Binding record to create.
			 */
			binding: BindingRecord;
	  }
	| {
			type: 'delete_binding';
			/**
			 * Binding to delete.
			 */
			binding_id: BindingId;
	  };

/**
 * Request metadata used to turn editor patches into one transaction draft.
 */
export type EditorReconciliationRequest = {
	/**
	 * Ordered semantic editor changes.
	 */
	patches: Array<EditorPatch>;
	/**
	 * Actor committing the resulting transaction.
	 */
	actor_id: ActorId;
	/**
	 * Origin retained in transaction history.
	 */
	origin: Origin;
	/**
	 * Stable transaction identifier.
	 */
	transaction_id: TransactionId;
	/**
	 * Human-readable history description.
	 */
	description: string;
	/**
	 * Client timestamp.
	 */
	timestamp: Timestamp;
};
