// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type ShapeProperties = { [key in string]: JsonValue };

/**
 *Stable identifier for a document.
 */
export type DocumentId = string;

/**
 *Stable identifier for a page.
 */
export type PageId = string;

/**
 *Stable identifier for a layer.
 */
export type LayerId = string;

/**
 *Stable identifier for a shape.
 */
export type ShapeId = string;

/**
 *Stable identifier for a binding.
 */
export type BindingId = string;

/**
 *Stable identifier for an embedded or linked asset.
 */
export type AssetId = string;

/**
 *Stable identifier for a human, agent, or system actor.
 */
export type ActorId = string;

/**
 *Opaque causal hash supplied by the CRDT implementation.
 */
export type ChangeHash = string;

/**
 *Stable identifier for a serialized contract.
 */
export type FormatId = string;

/**
 *Registry key for a shape definition.
 */
export type ShapeKind = string;

/**
 *Registry key for a binding definition.
 */
export type BindingKind = string;

/**
 * Milliseconds since the Unix epoch.
 */
export type Timestamp = number;

/**
 * Monotonic version of a record within the document history.
 */
export type RecordVersion = number;

/**
 * Opacity constrained to the inclusive range from zero to one.
 */
export type Opacity = number;

/**
 * Anchor used to place an item in an ordered child list without numeric indexes.
 */
export type SiblingAnchor<Id> =
	| { position: 'first' }
	| { position: 'last' }
	| { position: 'before'; sibling_id: Id }
	| { position: 'after'; sibling_id: Id };

/**
 * Two-dimensional point or vector in document coordinates.
 */
export type Vec2 = {
	/**
	 * Horizontal component.
	 */
	x: number;
	/**
	 * Vertical component.
	 */
	y: number;
};

/**
 * Fill rule used to determine the interior of a compound path.
 */
export type PathFillRule = 'nonzero' | 'evenodd';

/**
 * Whether the two cubic handles at an anchor move together.
 */
export type PathHandleMode = 'broken' | 'joined';

/**
 * One normalized drawing command in a path subpath.
 */
export type PathSegment =
	| {
			type: 'move';
			/**
			 * Destination point.
			 */
			to: Vec2;
	  }
	| {
			type: 'line';
			/**
			 * Destination point.
			 */
			to: Vec2;
	  }
	| {
			type: 'quadratic';
			/**
			 * Quadratic control point.
			 */
			control: Vec2;
			/**
			 * Destination point.
			 */
			to: Vec2;
	  }
	| {
			type: 'cubic';
			/**
			 * First cubic control point.
			 */
			control_1: Vec2;
			/**
			 * Second cubic control point.
			 */
			control_2: Vec2;
			/**
			 * Destination point.
			 */
			to: Vec2;
	  };

/**
 * One normalized subpath. Its first segment must be a move command; later
 * segments continue from the previous segment's destination.
 */
export type PathSubpath = {
	/**
	 * Ordered move, line, and Bézier segments.
	 */
	segments: Array<PathSegment>;
	/**
	 * Whether the final point connects back to the subpath's move point.
	 */
	closed: boolean;
	/**
	 * Optional per-anchor handle modes. Missing entries use broken handles.
	 */
	handle_modes?: Array<PathHandleMode> | null;
};

/**
 * Normalized geometry for a native path shape.
 */
export type PathGeometry = {
	/**
	 * Independent subpaths in document-local coordinates.
	 */
	subpaths: Array<PathSubpath>;
	/**
	 * Rule used when filling the compound path.
	 */
	fill_rule: PathFillRule;
};

/**
 * The resolved native geometry of one semantic arrow.
 */
export type ResolvedArrowGeometry = {
	/**
	 * The arrow shaft as native path segments in the arrow's local space.
	 */
	path: PathGeometry;
	/**
	 * Routing mode that produced the path, after applying automatic routing.
	 */
	routing: string;
	/**
	 * Resolved endpoints and retained waypoints in arrow-local coordinates.
	 *
	 * This is useful to editor clients that need to compare a projected
	 * resolution with an in-progress waypoint edit without inspecting the
	 * path's curve representation.
	 */
	waypoints: Array<Vec2>;
};

/**
 * Transform relative to a shape's parent container or layer.
 */
export type Transform = {
	/**
	 * Translation in parent coordinates.
	 */
	translation: Vec2;
	/**
	 * Clockwise rotation in radians.
	 */
	rotation: number;
	/**
	 * Horizontal scale.
	 */
	scale_x: number;
	/**
	 * Vertical scale.
	 */
	scale_y: number;
};

/**
 * Origin of a record or transaction.
 */
export type Origin = 'human' | 'agent' | 'sync' | 'system';

/**
 * Attribution retained with content.
 */
export type Provenance = {
	/**
	 * Actor responsible for the record's current form.
	 */
	actor_id: ActorId;
	/**
	 * Path by which the record entered the document.
	 */
	origin: Origin;
	/**
	 * Time at which this provenance entry was recorded.
	 */
	timestamp: Timestamp;
	/**
	 * Optional source identifier, such as an external reference or proposal ID.
	 */
	source: string | null;
};

/**
 * Human- and agent-readable meaning attached to a shape.
 */
export type SemanticMetadata = {
	/**
	 * Optional display name.
	 */
	name: string | null;
	/**
	 * Optional card title.
	 */
	title: string | null;
	/**
	 * Optional semantic selector such as `architecture.service`.
	 */
	role: string | null;
	/**
	 * Optional longer description.
	 */
	description: string | null;
	/**
	 * Optional card body.
	 */
	body: string | null;
	/**
	 * Searchable, user-defined tags.
	 */
	tags: Array<string>;
	/**
	 * Optional content source, such as a citation or file path.
	 */
	source: string | null;
	/**
	 * Optional external link associated with the content.
	 */
	link: string | null;
	/**
	 * Optional user-defined structured metadata. An empty map means no custom fields.
	 */
	custom_metadata: { [key in string]: JsonValue };
	/**
	 * Whether direct edits to this shape are prohibited.
	 */
	locked: boolean;
	/**
	 * Whether an agent may propose or apply edits to this shape.
	 */
	agent_editable: boolean;
	/**
	 * Attribution for the record.
	 */
	provenance: Provenance;
};

/**
 * Common visual style shared by all shape kinds.
 */
export type ShapeStyle = {
	/**
	 * Opacity applied to the complete shape.
	 */
	opacity: Opacity;
	/**
	 * Optional opacity override for fills.
	 */
	fill_opacity: Opacity | null;
	/**
	 * Optional opacity override for strokes.
	 */
	stroke_opacity: Opacity | null;
};

/**
 * Parent that owns a shape's sole draw-order entry.
 */
export type ShapeParent = { kind: 'layer'; id: LayerId } | { kind: 'shape'; id: ShapeId };

/**
 * Stack direction for container layout.
 */
export type StackDirection = 'horizontal' | 'vertical';

/**
 * Cross-axis alignment for laid-out children.
 */
export type LayoutAlignment = 'start' | 'center' | 'end' | 'stretch';

/**
 * Padding inside a layout container.
 */
export type Insets = {
	/**
	 * Top inset.
	 */
	top: number;
	/**
	 * Right inset.
	 */
	right: number;
	/**
	 * Bottom inset.
	 */
	bottom: number;
	/**
	 * Left inset.
	 */
	left: number;
};

/**
 * Optional automatic layout applied by a container shape.
 */
export type ContainerLayout =
	| { kind: 'free' }
	| {
			kind: 'stack';
			/**
			 * Flow direction.
			 */
			direction: StackDirection;
			/**
			 * Space between adjacent children.
			 */
			gap: number;
			/**
			 * Space between children and container edges.
			 */
			padding: Insets;
			/**
			 * Alignment on the cross axis.
			 */
			alignment: LayoutAlignment;
	  }
	| {
			kind: 'grid';
			/**
			 * Positive number of grid columns.
			 */
			columns: number;
			/**
			 * Horizontal gap between cells.
			 */
			column_gap: number;
			/**
			 * Vertical gap between cells.
			 */
			row_gap: number;
			/**
			 * Space between children and container edges.
			 */
			padding: Insets;
			/**
			 * Alignment within cells.
			 */
			alignment: LayoutAlignment;
	  };

/**
 * A shape record shared by all built-in shape definitions.
 */
export type ShapeRecord = {
	/**
	 * Stable record identifier.
	 */
	id: ShapeId;
	/**
	 * Registry key. Built-in values are exposed as `*_KIND` constants.
	 */
	kind: ShapeKind;
	/**
	 * Parent relation; ordering comes only from the parent's child list.
	 */
	parent: ShapeParent;
	/**
	 * Transform relative to `parent`.
	 */
	transform: Transform;
	/**
	 * Ordered children when this shape is a container. This list is the
	 * frame presentation and export order.
	 */
	child_ids: Array<ShapeId>;
	/**
	 * Optional automatic layout for container shapes.
	 */
	layout: ContainerLayout | null;
	/**
	 * Kind-specific serialized properties validated by the registry.
	 */
	properties: ShapeProperties;
	/**
	 * Human- and agent-readable semantics and permissions.
	 */
	metadata: SemanticMetadata;
	/**
	 * Visual properties common to all kinds.
	 */
	style: ShapeStyle;
	/**
	 * Version used by optimistic operation preconditions.
	 */
	version: RecordVersion;
};

/**
 * A page record and its ordered layer list.
 */
export type PageRecord = {
	/**
	 * Stable record identifier.
	 */
	id: PageId;
	/**
	 * User-visible page name.
	 */
	name: string;
	/**
	 * Layer IDs in back-to-front draw order.
	 */
	layer_ids: Array<LayerId>;
	/**
	 * Version used by optimistic operation preconditions.
	 */
	version: RecordVersion;
};

/**
 * A layer record and its ordered root-shape list.
 */
export type LayerRecord = {
	/**
	 * Stable record identifier.
	 */
	id: LayerId;
	/**
	 * Page that owns this layer.
	 */
	page_id: PageId;
	/**
	 * User-visible layer name.
	 */
	name: string;
	/**
	 * Root shape IDs in back-to-front draw order.
	 */
	shape_ids: Array<ShapeId>;
	/**
	 * Whether descendants participate in rendering and hit testing.
	 */
	visible: boolean;
	/**
	 * Whether descendants can be selected or changed.
	 */
	locked: boolean;
	/**
	 * Opacity inherited by descendants.
	 */
	opacity: Opacity;
	/**
	 * Version used by optimistic operation preconditions.
	 */
	version: RecordVersion;
};

/**
 * Attachment point on a bound shape.
 */
export type BindingAnchor =
	| { kind: 'center' }
	| {
			kind: 'edge';
			/**
			 * Normalized horizontal coordinate.
			 */
			x: number;
			/**
			 * Normalized vertical coordinate.
			 */
			y: number;
	  };

/**
 * Relationship between two shapes.
 */
export type BindingRecord = {
	/**
	 * Stable record identifier.
	 */
	id: BindingId;
	/**
	 * Registry key describing binding behavior.
	 */
	kind: BindingKind;
	/**
	 * Shape that owns the binding, such as an arrow.
	 */
	source_shape_id: ShapeId;
	/**
	 * Shape to which the source is bound.
	 */
	target_shape_id: ShapeId;
	/**
	 * Named source handle, such as `start` or `end`.
	 */
	source_handle: string;
	/**
	 * Attachment point on the target.
	 */
	anchor: BindingAnchor;
	/**
	 * Optional semantic relationship type, such as `depends_on`.
	 */
	relation_type?: string | null;
	/**
	 * Version used by optimistic operation preconditions.
	 */
	version: RecordVersion;
};

/**
 * Storage form for asset contents.
 */
export type AssetSource =
	| {
			kind: 'embedded';
			/**
			 * Raw asset bytes.
			 */
			bytes: Array<number>;
	  }
	| {
			kind: 'external';
			/**
			 * URI used to resolve the content.
			 */
			uri: string;
	  };

/**
 * The semantic target represented by a reference shape.
 */
export type ReferenceKind = 'url' | 'file' | 'page';

/**
 * Native reference content properties.
 */
export type ReferenceProperties = {
	/**
	 * Width of the reference card.
	 */
	width: number;
	/**
	 * Height of the reference card.
	 */
	height: number;
	/**
	 * Reference target kind.
	 */
	referenceType: ReferenceKind;
	/**
	 * URL, path, or page ID represented by the shape.
	 */
	value: string;
	/**
	 * Optional display label.
	 */
	label: string | null;
};

/**
 * Normalized image crop insets.
 */
export type ImageCrop = {
	/**
	 * Top inset as a fraction of the source image.
	 */
	top: number;
	/**
	 * Right inset as a fraction of the source image.
	 */
	right: number;
	/**
	 * Bottom inset as a fraction of the source image.
	 */
	bottom: number;
	/**
	 * Left inset as a fraction of the source image.
	 */
	left: number;
};

/**
 * Shape used to clip an image during rendering.
 */
export type ImageMaskKind = 'rectangle' | 'ellipse' | 'rounded';

/**
 * Native image mask properties.
 */
export type ImageMask = {
	/**
	 * Mask shape.
	 */
	kind: ImageMaskKind;
	/**
	 * Rounded-corner radius for a rounded mask.
	 */
	radius: number | null;
};

/**
 * Image, font, or other binary asset.
 */
export type AssetRecord = {
	/**
	 * Stable record identifier.
	 */
	id: AssetId;
	/**
	 * User-visible asset name.
	 */
	name: string;
	/**
	 * IANA media type.
	 */
	media_type: string;
	/**
	 * Content digest including its algorithm prefix.
	 */
	digest: string;
	/**
	 * Stored or linked content.
	 */
	source: AssetSource;
	/**
	 * Attribution for the asset.
	 */
	provenance: Provenance;
	/**
	 * Version used by optimistic operation preconditions.
	 */
	version: RecordVersion;
};

/**
 * Normalized, materialized Inkfinite document.
 */
export type Document = {
	/**
	 * Pages indexed by their stable IDs.
	 */
	pages: { [key in PageId]: PageRecord };
	/**
	 * Pages in user-visible order.
	 */
	page_ids: Array<PageId>;
	/**
	 * Layers indexed by their stable IDs.
	 */
	layers: { [key in LayerId]: LayerRecord };
	/**
	 * Shapes indexed by their stable IDs.
	 */
	shapes: { [key in ShapeId]: ShapeRecord };
	/**
	 * Bindings indexed by their stable IDs.
	 */
	bindings: { [key in BindingId]: BindingRecord };
	/**
	 * Assets indexed by their stable IDs.
	 */
	assets: { [key in AssetId]: AssetRecord };
};

/**
 * Materialized document plus its format and causal identity.
 */
export type DocumentSnapshot = {
	/**
	 * Stable format identifier.
	 */
	format: FormatId;
	/**
	 * Version of the document contract.
	 */
	format_version: number;
	/**
	 * Stable document identifier.
	 */
	document_id: DocumentId;
	/**
	 * Causal CRDT heads represented by this snapshot.
	 */
	heads: Array<ChangeHash>;
	/**
	 * Normalized records.
	 */
	document: Document;
};
