// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

import type { ActorId, ChangeHash, DocumentId, DocumentSnapshot, JsonValue, Origin, Timestamp } from "./model.js";
import type { CommitResult, DocumentPath, Proposal, ProposalId, Query, QueryResult, SaveResult, TransactionDraft } from "./transaction.js";

/**
 * Stable identifier for an open document session.
 */
export type SessionId = string;

/**
 * How authenticated agents may change one open desktop document.
 */
export type AgentAccessMode = "review" | "direct";

/**
 * Transport-independent request accepted by desktop commands, IPC, or CLI adapters.
 */
export type Request = { "type": "create_document",
/**
 * Stable identity for the new document.
 */
document_id: DocumentId,
/**
 * Actor that will own the session's local changes.
 */
actor_id: ActorId, } | { "type": "open_document",
/**
 * File to open.
 */
path: DocumentPath,
/**
 * Actor that will own the session's local changes.
 */
actor_id: ActorId, } | { "type": "snapshot",
/**
 * Open session to inspect.
 */
session_id: SessionId, } | { "type": "commit",
/**
 * Open session to change.
 */
session_id: SessionId,
/**
 * Transaction to validate and apply.
 */
transaction: TransactionDraft, } | { "type": "propose",
/**
 * Open session against which to validate.
 */
session_id: SessionId,
/**
 * Transaction to preview.
 */
transaction: TransactionDraft, } | { "type": "apply",
/**
 * Open session to change.
 */
session_id: SessionId,
/**
 * Transaction to validate and apply.
 */
transaction: TransactionDraft, } | { "type": "accept_proposal",
/**
 * Open session to change.
 */
session_id: SessionId,
/**
 * Proposal to accept.
 */
proposal_id: ProposalId,
/**
 * Zero-based operation positions to accept, or all operations when absent.
 */
operation_positions: Array<number> | null, } | { "type": "reject_proposal",
/**
 * Open session that owns the proposal.
 */
session_id: SessionId,
/**
 * Proposal to discard.
 */
proposal_id: ProposalId, } | { "type": "undo",
/**
 * Open session to change.
 */
session_id: SessionId,
/**
 * Actor whose transaction should be compensated.
 */
actor_id: ActorId, } | { "type": "save",
/**
 * Open session to persist.
 */
session_id: SessionId,
/**
 * Heads the caller expects to save.
 */
expected_heads: Array<ChangeHash>, } | { "type": "save_as",
/**
 * Open session to persist.
 */
session_id: SessionId,
/**
 * Replacement path.
 */
path: DocumentPath,
/**
 * Heads the caller expects to save.
 */
expected_heads: Array<ChangeHash>, } | { "type": "query",
/**
 * Open session to inspect.
 */
session_id: SessionId,
/**
 * Filters to apply.
 */
query: Query, } | { "type": "redo",
/**
 * Open session to change.
 */
session_id: SessionId,
/**
 * Actor whose transaction should be restored.
 */
actor_id: ActorId, } | { "type": "validate",
/**
 * Open session to validate.
 */
session_id: SessionId, } | { "type": "close",
/**
 * Session to close.
 */
session_id: SessionId, };

/**
 * Successful transport-independent response.
 */
export type Response = { "type": "session_opened", "value": SessionId } | { "type": "snapshot", "value": DocumentSnapshot } | { "type": "committed", "value": CommitResult } | { "type": "proposed", "value": Proposal } | { "type": "proposal_rejected" } | { "type": "saved", "value": SaveResult } | { "type": "query_result", "value": QueryResult } | { "type": "valid" } | { "type": "closed" };

/**
 * Stable protocol error returned across all adapters.
 */
export type ProtocolError = {
/**
 * Stable machine-readable error code.
 */
code: string,
/**
 * Human-readable error detail.
 */
message: string,
/**
 * Optional structured context for machine clients.
 */
details: JsonValue | null, };

