// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

import type { JsonValue, Transform } from "./model.js";
import type { Bounds } from "./transaction.js";

export const BUILTIN_SHAPE_KINDS = ["rect", "ellipse", "line", "arrow", "text", "stroke", "markdown", "container"] as const;
export type BuiltinShapeKind = typeof BUILTIN_SHAPE_KINDS[number];

export const GEOMETRY_CONVENTION = {
  coordinateSystem: "local_origin_top_left_positive_x_right_positive_y_down",
  rotation: "clockwise_radians_about_local_origin",
  bounds: "axis_aligned_enclosing_bounds",
} as const;

export const SHAPE_REGISTRY = BUILTIN_SHAPE_KINDS.map((kind) => ({
  kind,
  dimensions: ["width", "height"] as const,
  allowsChildren: kind === "container",
}));

function numericProperty(properties: Record<string, JsonValue>, name: string): number {
  const value = properties[name];
  return typeof value === "number" && Number.isFinite(value) ? value : 0;
}

export function validateShapeProperties(kind: string, properties: Record<string, JsonValue>): boolean {
  if (!(BUILTIN_SHAPE_KINDS as readonly string[]).includes(kind)) return false;
  return ["width", "height"].every((name) => {
    const value = properties[name];
    return value === undefined || (typeof value === "number" && Number.isFinite(value) && value >= 0);
  });
}

export type RegistryShape = {
  kind: string;
  properties: Record<string, JsonValue>;
  transform: Transform;
};

export function boundsForShape(shape: RegistryShape): Bounds {
  const width = Math.abs(numericProperty(shape.properties, "width"));
  const height = Math.abs(numericProperty(shape.properties, "height"));
  const { translation, rotation, scale_x: scaleX, scale_y: scaleY } = shape.transform;
  const cos = Math.cos(rotation);
  const sin = Math.sin(rotation);
  const points = [[0, 0], [width, 0], [0, height], [width, height]].map(([x, y]) => [
    translation.x + x * scaleX * cos - y * scaleY * sin,
    translation.y + x * scaleX * sin + y * scaleY * cos,
  ]);
  const xs = points.map(([x]) => x);
  const ys = points.map(([, y]) => y);
  const minX = Math.min(...xs);
  const maxX = Math.max(...xs);
  const minY = Math.min(...ys);
  const maxY = Math.max(...ys);
  return { x: minX, y: minY, width: maxX - minX, height: maxY - minY };
}
