// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

import type { AssetId, JsonValue, ShapeKind, ShapeStyle, Transform } from './model.js';

/**
 * An unsupported SVG feature identified during static import.
 */
export type SvgUnsupportedFeature =
	| 'gradient'
	| 'pattern'
	| 'clip_path'
	| 'mask'
	| 'filter'
	| 'script'
	| 'animation'
	| 'external_resource'
	| 'stylesheet';

/**
 * Action taken for unsupported SVG content during static import.
 */
export type SvgUnsupportedAction = 'omitted';

/**
 * A non-fatal condition encountered while importing an SVG.
 */
export type SvgImportWarning =
	| {
			kind: 'unsupported_element';
			/**
			 * Element name.
			 */
			element: string;
			/**
			 * Source element ID, when present.
			 */
			source_id: string | null;
			/**
			 * Reason for skipping it.
			 */
			reason: string;
	  }
	| {
			kind: 'unsupported_feature';
			/**
			 * Unsupported SVG feature.
			 */
			feature: SvgUnsupportedFeature;
			/**
			 * Element name.
			 */
			element: string;
			/**
			 * Source element ID, when present.
			 */
			source_id: string | null;
			/**
			 * Action taken by the importer.
			 */
			action: SvgUnsupportedAction;
	  }
	| {
			kind: 'unsupported_paint';
			/**
			 * Element name.
			 */
			element: string;
			/**
			 * Paint property name.
			 */
			property: string;
			/**
			 * Original paint value.
			 */
			value: string;
	  };

/**
 * A view box declared by the source SVG.
 */
export type SvgViewBox = {
	/**
	 * Horizontal origin in SVG user units.
	 */
	x: number;
	/**
	 * Vertical origin in SVG user units.
	 */
	y: number;
	/**
	 * Width in SVG user units.
	 */
	width: number;
	/**
	 * Height in SVG user units.
	 */
	height: number;
};

/**
 * A parsed SVG asset, either the original source or embedded raster data.
 */
export type SvgAsset = {
	/**
	 * Deterministic asset identifier derived from the bytes.
	 */
	id: AssetId;
	/**
	 * Suggested source filename for the asset.
	 */
	name: string;
	/**
	 * IANA media type, such as `image/png`.
	 */
	media_type: string;
	/**
	 * Content digest including its algorithm prefix.
	 */
	digest: string;
	/**
	 * Embedded asset bytes.
	 */
	bytes: Array<number>;
};

/**
 * One native shape produced by SVG mapping.
 */
export type SvgShape = {
	/**
	 * The source element's `id`, when present.
	 */
	source_id: string | null;
	/**
	 * Native Inkfinite shape kind.
	 */
	kind: ShapeKind;
	/**
	 * Transform relative to the containing SVG group.
	 */
	transform: Transform;
	/**
	 * Kind-specific native properties.
	 */
	properties: { [key in string]: JsonValue };
	/**
	 * Common native opacity values.
	 */
	style: ShapeStyle;
};

/**
 * A parsed group mapped to a native container candidate.
 */
export type SvgGroup = {
	/**
	 * The source group or root element's `id`, when present.
	 */
	source_id: string | null;
	/**
	 * Transform relative to the containing SVG group.
	 */
	transform: Transform;
	/**
	 * Container opacity values.
	 */
	style: ShapeStyle;
	/**
	 * Native container properties, including calculated width and height.
	 */
	properties: { [key in string]: JsonValue };
	/**
	 * Ordered child nodes in SVG paint order.
	 */
	children: Array<SvgImportNode>;
};

/**
 * An image node referencing an extracted embedded raster asset.
 */
export type SvgImage = {
	/**
	 * The source image element's `id`, when present.
	 */
	source_id: string | null;
	/**
	 * Extracted embedded asset.
	 */
	asset_id: AssetId;
	/**
	 * Transform relative to the containing SVG group.
	 */
	transform: Transform;
	/**
	 * Image properties, including width and height.
	 */
	properties: { [key in string]: JsonValue };
	/**
	 * Image opacity values.
	 */
	style: ShapeStyle;
};

/**
 * A normalized SVG node.
 */
export type SvgImportNode =
	| { kind: 'group'; value: SvgGroup }
	| { kind: 'shape'; value: SvgShape }
	| { kind: 'image'; value: SvgImage };

/**
 * A normalized SVG import result.
 */
export type SvgImport = {
	/**
	 * Root view box, when the source declared one.
	 */
	view_box: SvgViewBox | null;
	/**
	 * Root group containing the source SVG's visual children.
	 */
	root: SvgGroup;
	/**
	 * The original source retained for provenance and future fallback or re-import.
	 */
	source_asset: SvgAsset;
	/**
	 * Embedded raster assets referenced by image nodes.
	 */
	assets: Array<SvgAsset>;
	/**
	 * Non-fatal features skipped during parsing.
	 */
	warnings: Array<SvgImportWarning>;
};
