// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

import type {
  ActorId, AssetId, AssetRecord, BindingId, BindingRecord, ChangeHash, ContainerLayout,
  DocumentId, DocumentSnapshot, LayerId, LayerRecord, Opacity, Origin, PageId, PageRecord,
  RecordVersion, SemanticMetadata, ShapeId, ShapeParent, ShapeProperties, ShapeRecord,
  ShapeStyle, SiblingAnchor, Timestamp, Transform, JsonValue
} from "./model.js";

/**
 * Stable identifier for a transaction.
 */
export type TransactionId = string;

/**
 * One durable edit submitted to the transaction engine.
 */
export type TransactionDraft = { 
/**
 * Stable transaction identifier.
 */
id: TransactionId, 
/**
 * Actor responsible for the transaction.
 */
actor_id: ActorId, 
/**
 * Path by which the transaction entered the engine.
 */
origin: Origin, 
/**
 * Causal heads inspected by the caller.
 */
base_heads: Array<ChangeHash>, 
/**
 * Human-readable explanation retained in history.
 */
description: string, 
/**
 * Ordered operations committed as one CRDT change.
 */
operations: Array<Operation>, 
/**
 * Client-recorded transaction time.
 */
timestamp: Timestamp, };

/**
 * Cross-platform serialized document path used at file-service boundaries.
 */
export type DocumentPath = string;

/**
 * Policy for children of a deleted non-empty layer.
 */
export type LayerContentsDisposition = { "kind": "move_to", "destination_layer_id": LayerId } | { "kind": "delete" };

/**
 * Mutable layer fields.
 */
export type LayerPatch = { 
/**
 * Replacement display name.
 */
name: string | null, 
/**
 * Replacement visibility.
 */
visible: boolean | null, 
/**
 * Replacement locked state.
 */
locked: boolean | null, 
/**
 * Replacement inherited opacity.
 */
opacity: Opacity | null, };

/**
 * Mutable shape fields. `Some(None)` clears an optional field.
 */
export type ShapePatch = { 
/**
 * Replacement relative transform.
 */
transform: Transform | null, 
/**
 * Replacement kind-specific properties.
 */
properties: ShapeProperties | null, 
/**
 * Replacement semantic metadata.
 */
metadata: SemanticMetadata | null, 
/**
 * Replacement common style.
 */
style: ShapeStyle | null, 
/**
 * Replacement or removal of container layout.
 */
layout: ContainerLayout | null | null, };

/**
 * Mutable asset fields.
 */
export type AssetPatch = { 
/**
 * Replacement display name.
 */
name: string | null, 
/**
 * Replacement attribution source label.
 */
provenance_source: string | null | null, };

/**
 * Axis used by alignment and distribution operations.
 */
export type LayoutAxis = "horizontal" | "vertical";

/**
 * Edge or center line used to align a group of shapes.
 */
export type ShapeAlignment = "left" | "center" | "right" | "top" | "middle" | "bottom";

/**
 * Durable document operation. Ordered insertions use sibling anchors only.
 */
export type Operation = { "type": "create_page", 
/**
 * Complete new page record.
 */
page: PageRecord, 
/**
 * Placement relative to an existing page.
 */
anchor: SiblingAnchor<PageId>, } | { "type": "rename_page", 
/**
 * Page to rename.
 */
page_id: PageId, 
/**
 * Replacement name.
 */
name: string, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "delete_page", 
/**
 * Page to delete.
 */
page_id: PageId, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "create_layer", 
/**
 * Complete new layer record.
 */
layer: LayerRecord, 
/**
 * Placement relative to an existing layer.
 */
anchor: SiblingAnchor<LayerId>, } | { "type": "patch_layer", 
/**
 * Layer to change.
 */
layer_id: LayerId, 
/**
 * Requested field replacements.
 */
patch: LayerPatch, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "reorder_layer", 
/**
 * Layer to move.
 */
layer_id: LayerId, 
/**
 * New placement relative to a sibling layer.
 */
anchor: SiblingAnchor<LayerId>, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "delete_layer", 
/**
 * Layer to delete.
 */
layer_id: LayerId, 
/**
 * Required handling for existing shapes.
 */
contents: LayerContentsDisposition, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "create_shape", 
/**
 * Complete new shape record.
 */
shape: ShapeRecord, 
/**
 * Placement relative to an existing shape child.
 */
anchor: SiblingAnchor<ShapeId>, } | { "type": "patch_shape", 
/**
 * Shape to change.
 */
shape_id: ShapeId, 
/**
 * Requested field replacements.
 */
patch: ShapePatch, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "reparent_shape", 
/**
 * Shape to move.
 */
shape_id: ShapeId, 
/**
 * Replacement parent.
 */
parent: ShapeParent, 
/**
 * Placement relative to a child of the replacement parent.
 */
anchor: SiblingAnchor<ShapeId>, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "delete_shape", 
/**
 * Shape to delete.
 */
shape_id: ShapeId, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "create_binding", 
/**
 * Complete new binding record.
 */
binding: BindingRecord, } | { "type": "delete_binding", 
/**
 * Binding to delete.
 */
binding_id: BindingId, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "create_asset", 
/**
 * Complete new asset record.
 */
asset: AssetRecord, } | { "type": "patch_asset", 
/**
 * Asset to change.
 */
asset_id: AssetId, 
/**
 * Requested field replacements.
 */
patch: AssetPatch, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "delete_asset", 
/**
 * Asset to delete.
 */
asset_id: AssetId, 
/**
 * Optional optimistic record version.
 */
expected_version: RecordVersion | null, } | { "type": "align_shapes", 
/**
 * Shapes to align.
 */
shape_ids: Array<ShapeId>, 
/**
 * Alignment line shared by the shapes.
 */
alignment: ShapeAlignment, 
/**
 * Optional optimistic versions keyed by shape ID.
 */
expected_versions: { [key in ShapeId]: RecordVersion }, } | { "type": "distribute_shapes", 
/**
 * Shapes to distribute.
 */
shape_ids: Array<ShapeId>, 
/**
 * Axis on which to distribute the shapes.
 */
axis: LayoutAxis, 
/**
 * Optional optimistic versions keyed by shape ID.
 */
expected_versions: { [key in ShapeId]: RecordVersion }, };

/**
 * Identifies a record touched by a commit or proposal.
 */
export type RecordId = { "kind": "page", "id": PageId } | { "kind": "layer", "id": LayerId } | { "kind": "shape", "id": ShapeId } | { "kind": "binding", "id": BindingId } | { "kind": "asset", "id": AssetId };

/**
 * Materialized patch returned after a successful commit.
 */
export type DocumentPatch = { 
/**
 * Records created by the commit.
 */
created: Array<RecordId>, 
/**
 * Records changed by the commit.
 */
changed: Array<RecordId>, 
/**
 * Records deleted by the commit.
 */
deleted: Array<RecordId>, };

/**
 * Axis-aligned bounds in document coordinates.
 */
export type Bounds = { 
/**
 * Left edge.
 */
x: number, 
/**
 * Top edge.
 */
y: number, 
/**
 * Non-negative width.
 */
width: number, 
/**
 * Non-negative height.
 */
height: number, };

/**
 * Region that a renderer should consider dirty after a transaction.
 */
export type AffectedRegion = { 
/**
 * Page containing the changed visual content.
 */
page_id: PageId, 
/**
 * Union of the record's bounds before and after the change.
 */
bounds: Bounds, };

/**
 * Operations needed to compensate a committed transaction.
 */
export type InverseMetadata = { 
/**
 * Actor whose history owns this inverse.
 */
actor_id: ActorId, 
/**
 * Field-scoped compensating operations.
 */
operations: Array<Operation>, };

/**
 * Non-fatal repair or normalization performed during a commit or merge.
 */
export type Warning = { 
/**
 * Stable machine-readable warning code.
 */
code: string, 
/**
 * Human-readable warning detail.
 */
message: string, 
/**
 * Related records, if known.
 */
record_ids: Array<RecordId>, };

/**
 * Successful result from a durable transaction.
 */
export type CommitResult = { 
/**
 * Transaction that was committed.
 */
transaction_id: TransactionId, 
/**
 * Causal heads after the commit.
 */
heads: Array<ChangeHash>, 
/**
 * Materialized mirror update.
 */
patch: DocumentPatch, 
/**
 * All records affected directly or through repairs.
 */
affected_ids: Array<RecordId>, 
/**
 * Visual regions invalidated by the commit.
 */
affected_regions: Array<AffectedRegion>, 
/**
 * Metadata retained for actor-scoped undo.
 */
inverse: InverseMetadata, 
/**
 * Non-fatal repairs and normalization notes.
 */
warnings: Array<Warning>, };

/**
 * Optional semantic filters for a document query.
 */
export type Query = { 
/**
 * Match one exact record ID, regardless of record kind.
 */
id: string | null, 
/**
 * Match a page, layer, shape, or asset display name.
 */
name: string | null, 
/**
 * Match one exact semantic role.
 */
role: string | null, 
/**
 * Match one exact tag.
 */
tag: string | null, 
/**
 * Match one exact shape registry key.
 */
shape_kind: string | null, 
/**
 * Restrict the query to one page.
 */
page_id: PageId | null, 
/**
 * Restrict the query to one layer.
 */
layer_id: LayerId | null, 
/**
 * Restrict shapes to one direct parent.
 */
parent_id: string | null, 
/**
 * Restrict shapes to those intersecting these document bounds.
 */
bounds: Bounds | null, };

/**
 * Materialized query result suitable for machine clients.
 */
export type QueryResult = { 
/**
 * Causal heads inspected by the query.
 */
heads: Array<ChangeHash>, 
/**
 * Matching records in deterministic order.
 */
records: Array<RecordId>, 
/**
 * Bounds for matching shapes, in the same order as their shape records.
 */
bounds: { [key in ShapeId]: Bounds }, };

/**
 * Result of saving an open document session.
 */
export type SaveResult = { 
/**
 * Path written by the file service.
 */
path: DocumentPath, 
/**
 * Heads persisted by this save.
 */
heads: Array<ChangeHash>, };

/**
 * Stable identifier for a transaction proposal awaiting user review.
 */
export type ProposalId = string;

/**
 * Validated transaction held for explicit user review.
 */
export type Proposal = { 
/**
 * Stable proposal identifier.
 */
id: ProposalId, 
/**
 * Transaction validated against the listed heads.
 */
transaction: TransactionDraft, 
/**
 * Preview patch shown by the UI.
 */
preview: DocumentPatch, 
/**
 * Validation or repair warnings shown before acceptance.
 */
warnings: Array<Warning>, };

