// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
// Generated by Inkfinite's binding generator. Run `cargo run -p inkfinite-cli --bin generate-bindings`.

import type { Bounds, CommitResult, TransactionDraft } from './transaction.js';
import type { AssetId, DocumentSnapshot, FlattenedPath, ResolvedArrowGeometry, ShapeId } from './model.js';
import type { EditorProjection } from './editor.js';
import type { SvgImport, SvgImportWarning } from './svg-import.js';

/**
 * A structured failure returned by a browser document-engine operation.
 */
export type WasmDocumentSessionFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * State returned after opening or changing a browser document session.
 */
export type WasmDocumentSessionState = {
	/**
	 * Current canonical materialized snapshot.
	 */
	snapshot: DocumentSnapshot;
	/**
	 * Current Rust-owned editor projection.
	 */
	editor_projection: EditorProjection;
	/**
	 * Whether the session actor can compensate its latest transaction.
	 */
	can_undo: boolean;
	/**
	 * Whether the session actor can reapply its latest compensated transaction.
	 */
	can_redo: boolean;
};

/**
 * Result of a stateful browser document mutation.
 */
export type WasmDocumentMutationResponse =
	| {
			status: 'success';
			/**
			 * Materialized commit metadata.
			 */
			commit: CommitResult;
	  }
	| {
			status: 'error';
			/**
			 * Mutation failure details.
			 */
			error: WasmDocumentSessionFailure;
	  };

/**
 * A structured arrow geometry resolution failure.
 */
export type WasmArrowGeometryFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * Result of resolving one arrow through the Rust/WASM geometry boundary.
 */
export type WasmArrowGeometryResponse =
	| {
			status: 'success';
			/**
			 * Resolved arrow shaft and waypoints.
			 */
			geometry: ResolvedArrowGeometry;
	  }
	| {
			status: 'error';
			/**
			 * Resolution failure details.
			 */
			error: WasmArrowGeometryFailure;
	  };

/**
 * A structured native path metrics failure.
 */
export type WasmPathMetricsFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * Result of measuring one native path through the Rust/WASM geometry boundary.
 */
export type WasmPathMetricsResponse =
	| {
			status: 'success';
			/**
			 * Flattened path and its measured length.
			 */
			metrics: FlattenedPath;
	  }
	| {
			status: 'error';
			/**
			 * Measurement failure details.
			 */
			error: WasmPathMetricsFailure;
	  };

/**
 * Options accepted by the deterministic browser SVG renderer.
 */
export type WasmSvgRenderOptions = {
	/**
	 * Page to render, or the first page when omitted.
	 */
	page_id: string | null;
	/**
	 * Layers to include.
	 */
	layer_ids: Array<string>;
	/**
	 * Shapes to include.
	 */
	selection: Array<string>;
	/**
	 * Optional clipping region.
	 */
	region: Bounds | null;
	/**
	 * Font families available to the browser renderer.
	 */
	available_font_families: Array<string>;
	/**
	 * Asset IDs available to the browser renderer.
	 */
	available_asset_ids: Array<string>;
};

/**
 * A normalized SVG import failure.
 */
export type WasmSvgImportFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * Result of parsing SVG bytes without mutating a document.
 */
export type WasmSvgImportResponse =
	| {
			status: 'success';
			/**
			 * The normalized Rust import tree.
			 */
			import: SvgImport;
			/**
			 * Number of embedded image nodes omitted because their source data could not be represented.
			 */
			omitted_image_count: number;
	  }
	| {
			status: 'error';
			/**
			 * Import failure details.
			 */
			error: WasmSvgImportFailure;
	  };

/**
 * Result of importing SVG bytes into a browser document session.
 */
export type WasmSvgImportCommitResponse =
	| {
			status: 'success';
			/**
			 * Session state after the import.
			 */
			state: WasmDocumentSessionState;
			/**
			 * Non-fatal parser warnings.
			 */
			warnings: Array<SvgImportWarning>;
			/**
			 * Number of embedded image nodes omitted because their source data could not be represented.
			 */
			omitted_image_count: number;
			/**
			 * Native shape IDs created by the transaction.
			 */
			shape_ids: Array<ShapeId>;
			/**
			 * Retained source asset ID.
			 */
			source_asset_id: AssetId;
	  }
	| {
			status: 'error';
			/**
			 * Import failure details.
			 */
			error: WasmDocumentSessionFailure;
	  };

/**
 * A deterministic SVG render warning.
 */
export type WasmSvgRenderWarning = {
	/**
	 * Machine-readable warning category.
	 */
	code: string;
	/**
	 * Human-readable warning detail.
	 */
	message: string;
};

/**
 * A deterministic SVG render failure.
 */
export type WasmSvgRenderFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * Result of rendering a canonical browser snapshot.
 */
export type WasmSvgRenderResponse =
	| {
			status: 'success';
			/**
			 * Complete SVG markup.
			 */
			svg: string;
			/**
			 * Renderer warnings.
			 */
			warnings: Array<WasmSvgRenderWarning>;
	  }
	| {
			status: 'error';
			/**
			 * Render failure details.
			 */
			error: WasmSvgRenderFailure;
	  };

/**
 * An editor projection failure.
 */
export type WasmEditorProjectionFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * Result of projecting a canonical browser snapshot.
 */
export type WasmEditorProjectionResponse =
	| {
			status: 'success';
			/**
			 * Projected editor records and order.
			 */
			projection: EditorProjection;
	  }
	| {
			status: 'error';
			/**
			 * Projection failure details.
			 */
			error: WasmEditorProjectionFailure;
	  };

/**
 * An editor reconciliation failure.
 */
export type WasmEditorReconciliationFailure = {
	/**
	 * Machine-readable failure category.
	 */
	code: string;
	/**
	 * Human-readable failure detail.
	 */
	message: string;
};

/**
 * Result of translating semantic editor patches into a native transaction.
 */
export type WasmEditorReconciliationResponse =
	| {
			status: 'success';
			/**
			 * Transaction draft using the supplied causal heads.
			 */
			transaction: TransactionDraft;
	  }
	| {
			status: 'error';
			/**
			 * Reconciliation failure details.
			 */
			error: WasmEditorReconciliationFailure;
	  };
